version: 0.1

phases:
  build:
    commands:
      - chmod +x gradlew
      - ./gradlew build
  post_build:
    commands:
      - aws cloudformation package --template-file cloudformation-input-template.yml --s3-bucket java4lambda-bucket --output-template-file output-template.yml

artifacts:
  files:
    - output-template.yml
  discard-paths: yes